services:
  fastapi_app:
    build: 
      dockerfile: ./Dockerfile
    container_name: fastapi_app
    command: sh -c "uvicorn src.presentation.app:app --port=8000 --host=0.0.0.0"
    volumes:
      - ./settings.yaml:/settings.yaml:ro

  nginx:
    image: "nginx:1.27"
    restart: always
    ports: [ "443:443" ]
    depends_on:
      - fastapi_app
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
