services:
  fastapi_app:
    build: 
      dockerfile: ./Dockerfile
    container_name: fastapi_app
    command: sh -c "uvicorn src.presentation.app:app --port=8000 --host=0.0.0.0"
    volumes:
      - ./settings.yaml:/settings.yaml:ro
