[project]
name = "schedule-builder-backend"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.13",
    "asyncpg>=0.30.0",
    "authlib>=1.6.0",
    "colorlog>=6.9.0",
    "dishka>=1.6.0",
    "fastapi>=0.115.12",
    "numpy>=2.3.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "fastapi-swagger>=0.2.19",
    "pydantic-settings>=2.9.1",
    "pydantic[email]>=2.11.5",
    "pytz>=2025.2",
    "pyyaml>=6.0.2",
    "uvicorn>=0.34.2",
]

[project.optional-dependencies]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
]

[tool.black]
line-length=79
extend-exclude='''
(
    \.git
  | \.venv
)
'''

[tool.isort]
default_section = "THIRDPARTY" 
known_local_folder = ["src", "domain", "infrastructure", "presentation", "application"]
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"] 
skip = [".gitignore", "venv", ".venv"] 
multi_line_output = 3
line_length = 79
lines_after_imports = 2
include_trailing_comma = true