name: Build and publish a docker image for the API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set tag name
        id: set_tag_name
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name || 'latest' }}" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t wannebetheshy1/swp2025:${{ env.TAG_NAME }} .

      - name: Push image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push <your-dockerhub-username>/<your-dockerhub-repo>:${{ env.TAG_NAME }}
